### ISSUE TITLE
Add API To change Selected Value

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#12]
I want to change the selected value from outside.
Please provide api to change selected value.
Thank you.

**Comment by martinpengellyphillips** [comment]
I'm guessing you mean on the component? 

(The underlying`createSelect` has a `setValue` in case you are building a custom control).

What's your use case? Would making`initialValue` prop reactive work?

**Comment by kapilpipaliya** [comment]
I want to add clear button to the select input. when I press it selected value should be cleared. I think making `initialValue` reactive will work.

**Comment by martinpengellyphillips** [comment]
Makes sense. Feel free to issue a PR. Alternatively, I'll take a look at implementing this in the future.

**Comment by timothyallan** [comment]
Having it recognize a `selected` prop on the option would also allow Solid Select to work with forms libraries like Felte https://github.com/pablo-abc/felte/blob/main/packages/common/src/utils/domUtils.ts#L173

**Comment by martinpengellyphillips** [comment]
Interesting, but I think interop with something like Felte would be a separate feature. 

I'd expect in most cases to wrap Solid Select for use in a particular form library (or use custom components with the underlying `createSelect` primitive).

In this case, I don't think it would make sense to support `selected` on the option as it would imply being able to set it also to control the value, but the current component is geared more towards a single control than the composed approach.

**Comment by timothyallan** [comment]
Fair enough! That said, the boring ol HTML `<select>` can have its value initially set by `selected` being present in an option, and according to my first google result from W3Schools, can also be used to control the value as well, as long as you have "a JavaScript" :)
![Screen Shot 2022-05-02 at 12 35 25 PM](https://user-images.githubusercontent.com/1995135/166305263-57a4b0eb-ef96-44e0-8b92-959f7dfdd6c5.png)

**Comment by martinpengellyphillips** [comment]
Yeah, but the default Solid Select component doesn't give you direct access to the option components:

`<Select options={...} />`

So where would you set this?

(Of course you can compose your own component out of the building blocks, but then you could also add this behaviour too).

**Comment by timothyallan** [comment]
Personally I'd just set it in the `createMemo()` that delivers the options I'm providing to Solid Select, keep that as the source of truth for both the App + SS.

**Comment by martinpengellyphillips** [comment]
Ah, I thought you meant a `selected` prop on each option component. But now I think you mean something on the options data structure passed in?

**Comment by timothyallan** [comment]
Yeah, by options I was thinking about the `options` prop that SS takes in, which I mentally equate with the `<option>` that an html `<select>` takes. i.e. the equivalent of something like `{label:'abc', value:'def', selected:true}` however, what I forgot was that all falls apart with a 3rd party library trying to set the selected option, as it would require the component to expose the options like you mentioned above, sigh. Composing a custom component looks like the best option at this point!

**Comment by swizzley** [comment]
Not sure if this is the same issue or not, but I'm running into a similar issue where I want to set the initialValue dynamically from an onChange function in another select component. It sounds like this is not reactive and not possible in the current version, is that true?

**Comment by martinpengellyphillips** [comment]
@swizzley That's correct for the `Select` component (the underlying `createSelect` does expose a `setValue` API).

I think the best approach is to make the `initialValue` reactive in the Component (so a little effect to call the underlying `select.setValue` rather than passing straight through as an option to `createSelect`). Happy to accept a PR here, otherwise I might take a look this weekend.

**Comment by martinpengellyphillips** [comment]
This is now supported in [0.10.0](https://github.com/thisbeyond/solid-select/releases/tag/0.10.0) and an example (`Reset`) has been added to https://solid-select.com

**Comment by martinpengellyphillips** [comment]
And improved slightly in [0.11.0](https://github.com/thisbeyond/solid-select/releases/tag/0.11.0)
