### ISSUE TITLE
v0.11.0 not work with object array options

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#15]
When I use v0.11.0 I always see `bound readSignal` message.
Please check attached example:
https://codesandbox.io/s/pensive-rubin-6z8bsp?file=/src/index.tsx

**Comment by martinpengellyphillips** [comment]
`bound readSignal` is the display of the raw signal object.

In 0.11.0 you need to pass the resolved signal rather than the raw signal - see the release notes: https://github.com/thisbeyond/solid-select/releases/tag/0.11.0
