### ISSUE TITLE
When initialValue is changed `onChange` is fired.

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#16]
when `initialValue` is changed `onChange` should not fired.

**Comment by martinpengellyphillips** [comment]
Hmm. I feel it is more natural to have `onChange` fire in this case as the value did change.

What's your reason for it not? Is it causing an issue for you?

**Comment by kapilpipaliya** [comment]
`onChange` also fired when options are changes. 
its causing problems to me because I save new changes in `onChange` handler to submit on the server.

**Comment by kapilpipaliya** [comment]
sorry, I mean `initialValue` change.
It must not fire `onChange` when `initialValue` changes.

**Comment by martinpengellyphillips** [comment]
I disagree. I think it makes sense to fire because the value is changing effectively.

But I'm open to changing if you share some example to illustrate the issue you face and I can't think of a workaround.

**Comment by kapilpipaliya** [comment]
we have a form with many input components. each component modify the parent store when the value is changed. 
on submit we send the changed data to the backend. we are using solid-select for the select component. but select field is always changing parent store value, even if its not changed by the user.
we first display empty select field. then fetch the data for the selected value and then set the value. but the value is not actually changed by the user.

**Comment by martinpengellyphillips** [comment]
Wouldn't it be better to handle that logic in your store/sync rather than per form field? Keep track of the difference between what was on the server and what is in the form store and only save what changed.

I'm happy to look at this more if you share a working code example of the issue.

**Comment by kapilpipaliya** [comment]
thanks its good idea, but we have nested forms and its very complex to write this logic.

**Comment by martinpengellyphillips** [comment]
I think it is important that `onChange` is called when the value changes, even if via `initialValue`. Otherwise there is no way for a consumer to detect this change and they would have to add their reactivity at every call site that changes `initialValue` (consider dependent fields for example).

However, I think you can achieve what you want with a small `onChange` wrapper:

```jsx
const onChange = ...
<Select onChange={(value)=>value !== initialValue() && onChange(value)} />
```

**Comment by martinpengellyphillips** [comment]
Closing for now assuming that the example above is enough.

**Comment by Farnsi** [comment]
It is annoying to check in every select if the current value is !== initialValue.
Your example check is incomplete, you have to check too, if it has changed the first time, cause setting the select back later to initialValue wouldn't either execute onChange correctly.

Init settings should only set and not fire onChange, it could fire a custom onSetInitialValue (for whatever reason).
Reset a form should set current to the inital and fire an onChange.

@kapilpipaliya 
I solve this with a wrapper Component around Select to prevent this behavior.

**Comment by martinpengellyphillips** [comment]
Yeah, maybe I was wrong here/biased by my usage. I'll have another think about it.
