### ISSUE TITLE
`createOptions()` when passed `createable` function and return undefined should not create a option. 

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#19]
- https://github.com/thisbeyond/solid-select/blob/main/src/create-options.tsx#L66
I want the option should not be created if the createable function return undefined:
```
  const options = createOptions([], {
    disable: (value) => selectedValues().includes(value),
    createable: (value) => selectedValues().includes(value) ? undefined : value,
  });
```

**Comment by martinpengellyphillips** [comment]
Interesting. I'll have a think about this. There is logic that determines when to call this function, so it might be more appropriate to make that configurable rather than override the logic in the creator function.

**Comment by martinpengellyphillips** [comment]
Release [0.15.0](https://github.com/thisbeyond/solid-select/releases/tag/0.15.0) has now been published which should address this.
