### ISSUE TITLE
Hidden Input Opacity Not Changed On Blur(CSS Bug)

### ISSUE THREAD

**Issue by kapilpipaliya** [thisbeyond/solid-select#22]
when i click on the input and then click on outside the input, input opacity is not changed.

![2022-09-13_11-49_opacity_is_not_changed](https://user-images.githubusercontent.com/13032024/189825035-b3f629bb-7786-4c6d-ba7d-efe2bee26d18.png)

**Comment by martinpengellyphillips** [comment]
Ah, interesting. I'll take a look, but feel free to raise a pr also.

**Comment by rchandu** [comment]
@martinpengellyphillips I'm just starting to learn SolidJS. Can I check this out ?

**Comment by martinpengellyphillips** [comment]
@rchandu yes - go for it 🙂

**Comment by martinpengellyphillips** [comment]
Closing as superseded by [0.14.0](https://github.com/thisbeyond/solid-select/releases/tag/0.14.0) - the input is no longer hidden with opacity. Instead only the caret is hidden or not.
