### ISSUE TITLE
CreateOptions forced filterable to true

### ISSUE THREAD

**Issue by Lastofthefirst** [thisbeyond/solid-select#30]
When I created options with props = createOptions(value, {key:"speaker", filterable:false}) then included them with {...props} the component still acts as if filterable. Only way I found to prevent this was to stop using createOptions.

**Comment by martinpengellyphillips** [comment]
I'm not able to recreate that. Passing `filterable: false` works as expected in my test.

![solid-select-disable-filterable](https://user-images.githubusercontent.com/214338/200231974-e8cb4d65-736c-4c3b-891d-172bdb9395f9.gif)

**Comment by Lastofthefirst** [comment]
Oh yes, this is the same result I am getting, I thought filterable would disable the select as a text input. How do you do that?

**Comment by martinpengellyphillips** [comment]
Use the `readonly` prop on the `Select`.

**Comment by Lastofthefirst** [comment]
Ah, thats what I was looking for then. Please forgive the false alarm. Thank you for sharing your code and your time 😁
