### ISSUE TITLE
inline style

### ISSUE THREAD

**Issue by rooflesia** [thisbeyond/solid-select#33]
how to add inline style?

**Comment by martinpengellyphillips** [comment]
The builtin component doesn't support passing custom style to the various components beyond passing a custom style `class`.

**Comment by rooflesia** [comment]
so do you have any solution for example to add padding inside the select?

**Comment by martinpengellyphillips** [comment]
Yes - see the example for custom styling on https://solid-select.com/ and modify to add the padding you want. E.g in your CSS do the following and pass `class='custom'` to the select control.

```
.custom .solid-select-control {
  padding: 20px;
}
```

**Comment by rooflesia** [comment]
thanks martin excellent work!👏
