### ISSUE TITLE
Fuzzy sort on more than one key

### ISSUE THREAD

**Issue by xypnox** [thisbeyond/solid-select#41]
In the usual scenarios, having a single key to sort the list of data is fine, however, it might be useful to have an array of keys that can be used to match for the fuzzy finder and the higher match score will be used.

**Comment by martinpengellyphillips** [comment]
Do you have a specific use case in mind? I try to keep solid select opinionated but extensible so cautious in adding more "builtin". Would be good to see an example to play with.

**Comment by xypnox** [comment]
A few cases come to my mind,

1. The initial use case that I had was matching a nested set of links by either their entire path or by their name. a.b.c matches with abc and c
2. Matching name / description of a object
3. Matching category/name of a object

Sorry for the late reply.

**Comment by martinpengellyphillips** [comment]
I think it would be useful, but rather than increase the core size of this library I would recommend in your case to integrate a dedicated fuzzy search/sort library. So maybe this is more about providing a more composable way to add own search sort function to the `createOptions` helpers 🤔

**Comment by martinpengellyphillips** [comment]
Release [0.15.0](https://github.com/thisbeyond/solid-select/releases/tag/0.15.0) has now been published which makes this easier, though does not yet build in a multi-field fuzzySort. However, you can check out the new example on the website that shows one approach to do this: https://solid-select.com/?example=Filterable%2520%28Custom%29
