### ISSUE TITLE
Passing in ref not working

### ISSUE THREAD

**Issue by koolkao** [thisbeyond/solid-select#42]
When I pass in a reference like below, similar to the SolidJS tutorial, the ref ends up being undefined

let selectRef;
return <Select ref={selectRef}>

**Comment by martinpengellyphillips** [comment]
`ref` is not mapped to anything today in the default Select component. What are you trying to achieve?

**Comment by koolkao** [comment]
Thank you for the response. I'm trying to send focus to <Select>. Something like: 

`let ref;
<div onClick={ ()=> ref.focus() }>label</div>
<Select ref={ref}></Select>
`

Is there a better way to do this? thank you

**Comment by martinpengellyphillips** [comment]
I guess this should pass ref through to `Control` essentially. Will take a look at that.

**Comment by martinpengellyphillips** [comment]
Added in 2281a3cd39a7ca680b8fbce582c716ff4fbafd24 - will be available once released with an example on the website to match.

**Comment by martinpengellyphillips** [comment]
Release [0.15.0](https://github.com/thisbeyond/solid-select/releases/tag/0.15.0) has now been published which should address this. See new example at https://solid-select.com/?example=Focus%2520with%2520ref
