### ISSUE TITLE
Select interfers with ninja-keys

### ISSUE THREAD

**Issue by on3iro** [thisbeyond/solid-select#46]
Hey,

I just tried out solid-ninja-keys and stumbled over an issue, where I could not use ninja-keys default keybindings.
After narrowing it down, it turned out that `solid-select` somehow interferes with those bindings (tracking issue: https://github.com/wobsoriano/solid-ninja-keys/issues/1)

Any idea what could cause this and if there is an easy fix?
Here is a reproduction of the issue on stackblitz: https://stackblitz.com/edit/solidjs-templates-dz5buc?file=src%2FApp.tsx

Thanks in advance

**Comment by martinpengellyphillips** [comment]
Hmm, I'm not seeing the issue there. The bindings appear to work for me.

**Comment by on3iro** [comment]
Huh, that's weird. `cmd + k` works for me, but everything else doesn't. I wonder why it works for you. (I did not focus the select)

**Comment by on3iro** [comment]
@martinpengellyphillips we also checked the stackblitz on the computer of my wife (OSX as well) and the issue remains.

**Comment by martinpengellyphillips** [comment]
@on3iro please be clearer when reporting issues in future. I did not know from your original description that you were activating with `cmd + k` and then seeing an issue (I don't use `solid-ninja-keys` myself). With that additional context I am able to reproduce the issue.

However, replacing solid-select with a plain input and `onKeyDown` handler also presents the same issue. So I believe this is an issue with `solid-ninja-keys`. I imagine it relies on a library that uses dom event listeners directly and these may encounter issues when using solidjs delegated handlers (e.g. via something like `onKeyDown`). 

-> "Solid uses semi-synthetic event delegation for common UI events that are composed and bubble."

**Comment by on3iro** [comment]
@martinpengellyphillips oh good point, sorry. I usually try to be very specific inside my issue descriptions, but definitely missed the mark here.

I'll close the issue and report back to solid-ninja-keys or probably even `ninja-keys` (I had the same issue with ninja-keys).
Thanks for taking a look into this!
