### ISSUE TITLE
How to define predefined values ?

### ISSUE THREAD

**Issue by gxanshu** [thisbeyond/solid-select#47]
is there any way to pre define the value in the Select box
here is the thing that i want to do let suppose
```jsx
const [value, setValue] = createSignal<string[]>(['apple', 'banana'])
const preValue = ['apple']
```

and then use that state in the select component
```jsx
<Select
     multiple
     options={value()}
      value={preValue} // want to do something like that to already add apple and banana as selected
      onChange={setValue}
 />
```

**Comment by martinpengellyphillips** [comment]
Use `initialValue` instead of `value` and it should work. See [kitchen sink](https://solid-select.com/?example=Kitchen%2520Sink) example.
