### ISSUE TITLE
Enable custom remove button when the selector supports multiple values

### ISSUE THREAD

**Issue by LouisLuBrain** [thisbeyond/solid-select#53]
Can we provide a custom render function for the remove button, since the close button is too small to click and I want to use an icon?
<img width="423" alt="Screen Shot 2024-02-26 at 3 41 30 PM" src="https://github.com/thisbeyond/solid-select/assets/40519757/f0a52e2d-8d28-4c2a-a15b-8dfb4ff2ba35">

**Comment by martinpengellyphillips** [comment]
I don't want this library to bloat into supporting all manner of customisations at each level. Instead, I'd prefer it to be sensible out-of-the-box, but also provide a set of building blocks to do your own thing. 

So I won't add a custom render function for the remove button. But you can try:
1. Seeing how far you get with customising the CSS for the class `solid-select-multi-value-remove`
2. Creating your own component from the provided building blocks / integrate with another UI library (see http://localhost:5173/?example=SUID%2520Integration for an example)
