### ISSUE TITLE
ESBuild warning

### ISSUE THREAD

**Issue by CoWayger** [thisbeyond/solid-select#55]
Hi, this library produces warning in esbuild when importing css just like in example:

[WARNING] Ignoring this import because "node_modules/@thisbeyond/solid-select/dist/esm/style.css" was marked as having no side effects [ignored-bare-import]

Is marking sideEffects good stated in package.json?

Thank you

**Comment by martinpengellyphillips** [comment]
I presume this is in your code? I'm not sure how the library could produce the warning at it doesn't import the css itself. I find it odd that esbuild culls a css import 🤷 

Not sure how I can help without more info / reproducible example, so closing for now.
