### ISSUE TITLE
Can this component group by a tag

### ISSUE THREAD

**Issue by ray-delossantos** [thisbeyond/solid-select#6]
Do you believe that in the scope of this component makes sense to handle groups when rendering the options of the select?. 

Ex:
```html
<select>
  <optgroup label="Group">
  <option>
  ...
```

**Comment by ray-delossantos** [comment]
I believe there should be some examples for this advanced but common usage on a multi select component. Is the website of this component open to contributions? If you're participating in Solid Hack, then maybe after the hackaton I'll like to contribute.

Ex:

> https://react-select.com/home
In the group section, there's an example.

**Comment by martinpengellyphillips** [comment]
I've made the associated website public now: https://github.com/thisbeyond/solid-select-site

The `react-select` example seems to rely on a predefined data structure - something I am not sure about pursuing as a requirement yet. Will be interesting to see how you approach an example here 😄

**Comment by martinpengellyphillips** [comment]
@ray-delossantos - how did you get on? Any example you'd like to share or shall I close this issue for now?
