### ISSUE TITLE
Transparent background on options list

### ISSUE THREAD

**Issue by robodna** [thisbeyond/solid-select#60]
I used npm to install SolidSelect.  When I click on the component to show the options list, the list background is transparent so the background shows through.  Should it work with default style or do I need to modify it somehow?

Thank you

**Comment by martinpengellyphillips** [comment]
Originally I was going for bare styles only, but I agree some more sensible defaults are useful (see also #35). I'll be releasing a new version soon that addresses this (see commit 441a2466eff8b8a9c9f1f362602eae3e98a76222)

**Comment by robodna** [comment]
I just set the background for the options in a custom css file and all seems to work well now.

Thanks!

**Comment by martinpengellyphillips** [comment]
Release [0.15.0](https://github.com/thisbeyond/solid-select/releases/tag/0.15.0) has now been published which should address this.
