### ISSUE TITLE
Option Key and Value

### ISSUE THREAD

**Issue by robodna** [thisbeyond/solid-select#61]
My options are an array of objects with "id" and "name" properties.  How do I specify the key and value fields?

Thanks

**Comment by martinpengellyphillips** [comment]
Pass your array in as the `options` for `Select` and then specify a [custom `format` function](https://solid-select.com/?example=Format) to pick the field (e.g. `name`) you want to display. 

If you are using `createOptions` helper, you can [specify `key`](https://solid-select.com/?example=Format) instead for the basic case.

Note that `solid-select` will pass through your full objects as the value. For example, `onChange` will receive the full object for you to use.

**Comment by robodna** [comment]
Ok, that worked, thanks.
