### ISSUE TITLE
Open select list is covered up by other elements

### ISSUE THREAD

**Issue by robodna** [thisbeyond/solid-select#62]
I have a solid select element positioned near the bottom of a form.  When I click to open, the select list is covered over by a bottom toolbar ( z-index 20 ).  I"m unable to raise ( z-index 21)  the options select list over the toolbar since the select box itself needs to be behind the bottom toolbar ( z-index 20 ), but the select box's options list needs to be shown ABOVE the bottom toolbar.

Any ideas on how to get around this issue?

Thanks,

**Comment by robodna** [comment]
UPDATE: This was solved by setting the select's z-index to auto.

**Comment by martinpengellyphillips** [comment]
Cool. Do you mean you set the `z-index` on the the select list only or the whole select container?

Note for future - should we make the default `Select` use a portal to avoid these in future. Would require more explicit positioning and sizing (e.g. potentially using [floating-ui](https://floating-ui.com/) as lightweight solution.

**Comment by robodna** [comment]
I set the z-index on <Select class="z-auto" and then created a custom stylesheet with z-index:21 for .solid-select-list

I think a portal would be the right choice since that is what native elements like the select list seem to do, but not sure.
