### ISSUE TITLE
createAsyncOptions

### ISSUE THREAD

**Issue by aguilera51284** [thisbeyond/solid-select#9]
how i can use createAsyncOptions with object return,  i need a usage similar to createOptions :(

example: 

```
const fetchData = async (inputValue) => {
  if (!inputValue) {
    return [];
  }
  if (inputValue.length <= 3) {
    return [];
  }
  console.log("Buscar", inputValue);
  try {
    const games = await http.get('games', {
      $search: inputValue,
    });
    return games.map((game) => ({ name: game.name, id: game.id }));
  } catch (error) {
    return [];
  }
};
```

currently i get this
![image](https://user-images.githubusercontent.com/7749319/162551105-19c1b7fe-8a0d-467b-b67e-3003cc1e9112.png)

thx for this lib :)

**Comment by martinpengellyphillips** [comment]
Pass a custom `format` prop - for example:

```jsx
const props = createAsyncOptions(fetchData);
const format = (item) => item.name;
return <Select format={format} {...props} />;
```

**Comment by aguilera51284** [comment]
another question, with createAsyncOptions, you can put the "createable" option :)?

**Comment by martinpengellyphillips** [comment]
They are just helpers for configuring the component. Take a look at the source code of each and you'll see how they return appropriate props. So you _can_ do anything they do, but the helpers are focused on just a few things for convenience :)

In the case of a createable option - there would be lots that is specific to the async callback so didn't make sense to make this part of the helper. But you can configure manually (even make your own helper) to achieve what you want.

**Comment by Farnsi** [comment]
@aguilera51284 

For a createable a simple solution is to add the typed word at the beginning of the list. With enter it will be added.
Hacky solution and works only with `multiple`.

```
const props = createAsyncOptions(fetchData)

function fetchData(input) {
  // your fetch logic
  // e.g. a simple list
  let results = ['apple', 'banana']

  // add your typed word at the beginning of the list
  results.unshift(input)

  // your filter logic
  return results
}
```
